/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package snd;

/**
 *
 * @author MELENDRES_COMP111
 */
public class n extends javax.swing.JDialog {

    /**
     * Creates new form n
     */
    public n(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quetient = new javax.swing.JButton();
        answer = new javax.swing.JLabel();
        number2 = new javax.swing.JTextField();
        number1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sum = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        product = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("AcadEref", 0, 18)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quetient.setText("quetient");
        quetient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quetientActionPerformed(evt);
            }
        });
        getContentPane().add(quetient, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        answer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        answer.setText("  ");
        answer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 154, 110, 40));

        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });
        getContentPane().add(number2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 70, 240, -1));

        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });
        getContentPane().add(number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 40, 240, -1));

        jLabel1.setText("answer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 40));

        jLabel2.setText("number 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 40, 60, -1));

        jLabel3.setText("number 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 40, 60, 80));

        jLabel4.setText("number 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 40, 60, -1));

        jLabel5.setText("number 1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 40, 60, -1));

        sum.setText("sum");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        getContentPane().add(sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        minus.setText("minus");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        getContentPane().add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        product.setText("product");
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        getContentPane().add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quetientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quetientActionPerformed
  
   
 String s=number2.getText();
  String c=number1.getText();
        
         double numb=Double.parseDouble(s);
         double nume=Double.parseDouble(c); 
         double a=nume/numb;
       
      
         answer.setText(String.valueOf(a)); 
    }//GEN-LAST:event_quetientActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
       String b=number2.getText();
         double nume=Double.parseDouble(b);
           String c=number1.getText();
          double num=Double.parseDouble(c);// TODO add your handling code here:
           double a=nume/num;
       
      
         answer.setText(String.valueOf(a));
          
    }//GEN-LAST:event_number2ActionPerformed

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
      String b=number2.getText();
         double nume=Double.parseDouble(b);
           String c=number1.getText();
          double num=Double.parseDouble(c);// TODO add your handling code here:
           double a=nume/num;
       
      
         answer.setText(String.valueOf(a));
    }//GEN-LAST:event_number1ActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
      String b=number2.getText();
         double nume=Double.parseDouble(b);
           String c=number1.getText();
          double num=Double.parseDouble(c); // TODO add your handling code here:
           double a=nume+num;
       
      
         answer.setText(String.valueOf(a));
    }//GEN-LAST:event_sumActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        String b=number2.getText();
         double nume=Double.parseDouble(b);
           String c=number1.getText();
          double num=Double.parseDouble(c);// TODO add your handling code here:
           double a=num-nume;
       
      
         answer.setText(String.valueOf(a));
    }//GEN-LAST:event_minusActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
       String b=number2.getText();
         double nume=Double.parseDouble(b);
           String c=number1.getText();
          double num=Double.parseDouble(c);// TODO add your handling code here:
           double a=nume*num;
       
      
         answer.setText(String.valueOf(a));
    }//GEN-LAST:event_productActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                n dialog = new n(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton minus;
    private javax.swing.JTextField number1;
    private javax.swing.JTextField number2;
    private javax.swing.JButton product;
    private javax.swing.JButton quetient;
    private javax.swing.JButton sum;
    // End of variables declaration//GEN-END:variables
}
